New workflow step to upload original images to CESNET GitLab, fixes in oarepo version in invenio forks

diff --git a/.github/workflows/04-create-fork.yaml b/.github/workflows/04-create-fork.yaml
--- a/.github/workflows/04-create-fork.yaml
+++ b/.github/workflows/04-create-fork.yaml
@@ -203,6 +203,14 @@ jobs:
             apply_feature $feature_name $feature_base
           done
           
+          if [ -f "oarepo-after-patch.sh" ]; then
+            echo "Running oarepo-after-patch.sh"
+            bash oarepo-after-patch.sh || {
+              echo "oarepo-after-patch.sh failed"
+              exit 1
+            }
+          fi
+          
       - name: Create a summary of the changes and commit it
         run: | 
           cd .forks/${PACKAGE}
